var html =
'<ul>'
  +'<li>'
  +'<a href="About.html">About</a></li>'
  + '<li>'
    + '<a href="#">Application<span class="arrow">&#9660</span></a>'
    + '<ul>'
      + '<li><a href="">Volunteering with OT</a>'
      + '<ul>'
        + '<li><a href="Application/Getting an OT Volunteering Position.html">Getting the Position</a></li>'
        + '<li><a href="Tactics.html">Tactics</a></li>'
      + '</ul>'
      + '</li>'

      + '<li>'
        + '<a href="#">Extracurricular Activities</a>'
        + '<ul>'
          + '<li><a href="Application/Extracurricular Activities/Research.html">Research</a></li>'
          + '<li><a href="Application/Extracurricular Activities/Outside.html">Community Service</a></li>'
        + '</ul>'
      + '</li>'

      + '<li>'
        + '<a href="#">Recommendation</a>'
        + '<ul>'
          + '<li><a href="Get.html">Getting a recommender</a></li>'
          + '<li><a href="Rmaterials.html">Recommendation Materials</a></li>'
          + '<li><a href="Statement.html">Personal Statement</a></li>'
          + '<li><a href="CV.html">CV(or Resume)</a></li>'
          + '<li><a href="RecSummary.html">Recommendation Summary</a></li>'
        + '</ul>'
        + '</li>'

        + '<li><a href="Statement.html">Personal Statement</a></li>'
        + '<li><a href="Application/Choosing Schools.html">Choosing Schools</a></li>'
		+'<li><a href="Prerequisites.html">OT School Prerequisites</a></li>'
		
      + '</li>'
    + '</ul>'
  + '</li>'

  + '<li>'
    + '<a href="#">Interview<span class="arrow">&#9660</span></a>'
    + '<ul>'
      + '<li>'
        + '<a href="#">Interview Strategies</a>'
        + '<ul>'
          + '<li><a href="Interview Strategies/General.html">General rule</a></li>'
          + '<li><a href="Interview Strategies/Group.html">Group Interview</a></li>'
          + '<li><a href="Interview Strategies/One.html">Individual (One on one) Interview</a></li>'
        + '</ul>'
      + '</li>'

      + '<li><a href="Questions.html">Interview Questions</a></li>'

      + '<li>'
        + '<a href="#">Interview Trips</a>'
        + '<ul>'
          + '<li><a href="Huntington.html">Huntington University</a></li>'
          + '<li><a href="Rush.html">Rush University</a></li>'
          + '<li><a href="Salus.html">Salus University</a></li>'
          + '<li><a href="TJU.html">Thomas Jefferson University</a></li>'
        + '</ul>'
      + '</li>'
    + '</ul>'
  + '</li>'

  + '<li>'
    + '<a href="#">OT Crash Course<span class="arrow">&#9660</span></a>'
    + '<ul>'
      + '<li><a href="Mustknow.html">MUST KNOW Concepts</a></li>'
      + '<li>'
        + '<a href="#">OT fundamentals</a>'
        + '<ul>'
          + '<li><a href="SPD.html">Sensory Processing Disorder</a></li>'
          + '<li><a href="Evals.html">OT Evaluations</a></li>'
        + '</ul>'
      + '</li>'
    + '</ul>'
  + '</li>'

  + '<li>'
    + '<a href="#">Important Letters<span class="arrow">&#9660</span></a>'
    + '<ul>'
      + '<li><a href="ThankYou.html">Thank You Letters</a></li>'
      + '<li><a href="Withdraw.html">Withdraw Letters</a></li>'
      + '<li><a href="Deposit.html">Deposit Info</a></li>'
    + '</ul>'
  + '</li>'
+ '</ul>';

document.getElementById("main_nav").innerHTML = html;

